fix(web): use docker hub images (#611)
since we changed to use github runners, we should use docker hub images, or we will run into the following error

Run docker build web --file web/Dockerfile --tag
$ECR_REPOSITORY:$IMAGE_TAG
Sending build context to Docker daemon 1.135MB

Step 1/8 : FROM public.ecr.aws/docker/library/node:18.16 as builder
18.16: Pulling from docker/library/node
toomanyrequests: Rate exceeded
Error: Process completed with exit code 1.